"""Materialize the editorially checked question batch as linked Sanity documents.

Each row is a distinct source-specific question, not a generated paraphrase variant.
Review source passages and scope notes before extending this list.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "sanity/seed/investor-protection-questions.json"
OBSERVED = "2026-09-25T00:00:00Z"

SOURCES = {
    "esa22": ("source-esa-crypto-consumer-warning-2022-03-17", "EU financial regulators warn consumers on the risks of crypto-assets", "https://www.esma.europa.eu/press-news/esma-news/eu-financial-regulators-warn-consumers-risks-crypto-assets", "2022-03-17T00:00:00Z", "Joint warning by the EBA, ESMA and EIOPA to EU consumers in March 2022. It predates the later MiCA regime and does not state the current rights of an individual investor."),
    "esa25": ("source-esa-mica-consumer-warning-2025-10-06", "EU Supervisory Authorities warn consumers of risks and limited protection for certain crypto-assets and providers", "https://www.esma.europa.eu/press-news/esma-news/eu-supervisory-authorities-warn-consumers-risks-and-limited-protection-certain", "2025-10-06T00:00:00Z", "Joint EU consumer warning by the EBA, EIOPA and ESMA. Describes categories and checks under MiCA as of October 2025; it cannot establish a provider's current authorisation or guarantee recovery for an individual case."),
    "eba25": ("source-eba-esma-defi-report-2025-01-16", "The EBA and ESMA analyse recent developments in crypto-assets", "https://www.esma.europa.eu/press-news/esma-news/eba-and-esma-analyse-recent-developments-crypto-assets", "2025-01-16T00:00:00Z", "EBA and ESMA summary of a joint report on DeFi and crypto lending, borrowing and staking. Market estimates and risk observations are dated 2025 analysis, not current measures or findings about a named protocol."),
    "esaFraud": ("source-esa-online-fraud-factsheets-2025-12-15", "ESAs publish key tips to help consumers detect, prevent, and act on online frauds and scams", "https://www.esma.europa.eu/press-news/esma-news/esas-publish-key-tips-help-consumers-detect-prevent-and-act-online-frauds-and", "2025-12-15T00:00:00Z", "Joint EU authorities' consumer announcement introducing fraud factsheets. Examples and preventive tips are educational; they cannot identify whether a particular message or person is genuine."),
    "finra25": ("source-finra-investment-group-imposter-2025-12-09", "Investor Alert: Social Media ‘Investment Group’ Imposter Scams Continue to Rise", "https://www.finra.org/investors/insights/investment-group-imposter-scams", "2025-12-09T00:00:00Z", "FINRA US investor alert about reported social-media investment-group scams, including crypto pitches. Reported patterns are historical warnings, not a finding that any specific group or individual is fraudulent."),
    "secScams24": ("source-sec-five-crypto-scams-2024-05-29", "5 Ways Fraudsters May Lure Victims Into Scams Involving Crypto Asset Securities", "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-alerts/crypto-scams", "2024-05-29T00:00:00Z", "SEC Office of Investor Education and Advocacy staff alert. Describes hypothetical and reported fraud tactics, not findings about a named opportunity or a Commission rule."),
    "secYield22": ("source-sec-crypto-interest-accounts-2022-02-14", "Investor Bulletin: Crypto Asset Interest-bearing Accounts", "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/investor-bulletin-crypto-asset-interest-bearing-accounts", "2022-02-14T00:00:00Z", "SEC investor education bulletin about crypto interest-bearing accounts at publication. Insurance descriptions and the BlockFi order are historical and do not determine current account coverage or a company's current legal status."),
    "secRelation24": ("source-sec-relationship-investment-scams-2024-09-10", "Relationship Investment Scams – Investor Alert", "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-alerts/relationship-investment-scams-investor-alert", "2024-09-10T00:00:00Z", "Joint SEC, CFTC, FINRA and NASAA investor alert on relationship investment scams. Illustrative warning signs do not establish that an individual correspondent is a fraudster."),
    "secChats25": ("source-sec-group-chat-scams-2025-12-22", "Group Chats as a Gateway to Investment Scams – Investor Alert", "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-alerts/gateway-to-investment-scams", "2025-12-22T00:00:00Z", "SEC Office of Investor Education and Assistance staff alert. Morocoin allegations are SEC charges, not a final adjudication; general examples are not findings about a named chat."),
    "finraRelation25": ("source-finra-relationship-scams-2025-05-28", "Relationship Investment Scams: What They Are and Tips to Avoid Them", "https://www.finra.org/investors/insights/avoiding-relationship-investment-scams", "2025-05-28T00:00:00Z", "FINRA investor education article on historical relationship investment scam patterns and diligence. Cannot validate a live platform, account or person."),
}

# slug, source key or an existing source ID, distinct question, source-backed claim, reader context
QUESTIONS = [
    ("eu-total-loss-2022", "esa22", "What did EU supervisors warn about losing an entire crypto investment in 2022?", "The joint EU supervisory warning said consumers buying many crypto-assets faced a real possibility of losing all the money invested.", "This is the 2022 consumer warning, not a prediction for a particular asset or today's portfolio."),
    ("eu-misleading-ads-2022", "esa22", "How did the 2022 EU warning describe misleading crypto advertisements?", "The EBA, ESMA and EIOPA told consumers to watch for misleading crypto promotions, including advertisements through social media and influencers.", "Marketing language is not evidence of a product's risk or legal status."),
    ("eu-fast-returns-2022", "esa22", "Why did EU supervisors single out promises of fast crypto returns?", "The joint 2022 warning urged particular caution about promises of fast or high returns, especially offers that appear too good to be true.", "A promised return is a warning sign to investigate, not proof that a specific offer is fraudulent."),
    ("eu-recourse-2022", "esa22", "What did the 2022 EU warning say about recourse for crypto consumers?", "The authorities warned that crypto-assets and related services often fell outside existing EU financial-services protections at that publication date, limiting recourse for consumers.", "The 2022 position predates later regulation and cannot decide anyone's present legal rights."),
    ("eu-payment-suitability-2022", "esa22", "Did the 2022 EU warning treat crypto as suitable for most retail payments?", "The 2022 joint warning said many crypto-assets were not suited to most retail consumers as an investment or as a means of payment or exchange.", "This is a broad historical consumer warning, not advice on an individual transaction."),
    ("eu-social-promotion-2022", "esa22", "What role did social-media promotion play in the 2022 EU crypto warning?", "The authorities described aggressive public promotion of crypto-assets, including through social media, as context for their consumer warning.", "The warning addresses the marketing environment without assessing a particular promoter."),
    ("eu-highly-speculative-2022", "esa22", "How did the EU supervisors characterize many crypto-assets in 2022?", "The EBA, ESMA and EIOPA jointly warned that many crypto-assets were highly risky and speculative.", "The description concerns many assets as a category, not a measured risk score for a named token."),
    ("mica-provider-authorisation-2025", "esa25", "What provider check did EU supervisors recommend in October 2025?", "The EU authorities recommended checking whether a crypto-asset service provider was authorised in the EU before using it.", "A dated recommendation is no substitute for checking the current official register and the exact legal entity."),
    ("mica-wallet-security-2025", "esa25", "What did EU supervisors recommend checking about crypto wallets?", "The October 2025 warning advised consumers to ensure that wallets used to store crypto-assets were sufficiently secured.", "The source provides a general precaution, not a security assessment of any wallet."),
    ("mica-product-risk-2025", "esa25", "Why learn about a crypto product before investing under the EU warning?", "The EU authorities recommended learning about the crypto product or service and evaluating its risk before investing.", "The warning does not endorse any individual product or investment strategy."),
    ("mica-coverage-varies-2025", "esa25", "Does MiCA give identical protection for every crypto-asset?", "The October 2025 EU warning said consumer protection, if any, can be limited and can vary by the type of crypto-asset and service.", "The source does not determine which protections attach to a particular token or account today."),
    ("mica-scope-2025", "esa25", "Did the 2025 EU warning say MiCA covers every crypto-asset?", "The supervisors described MiCA as applying to certain types of crypto-assets, with a supervisory regime for relevant issuers and service providers.", "The publication distinguishes covered categories; an individual token still needs a separate legal classification."),
    ("mica-claims-handling-2025", "esa25", "What claims-handling limitation did EU supervisors identify?", "The 2025 warning said some consumers may lack a transparent and uniform claims-handling procedure for the crypto-assets or services they use.", "This is a category-level consumer warning, not a finding about a particular provider's complaints process."),
    ("mica-information-2025", "esa25", "What information gaps did the 2025 EU warning flag?", "The supervisors warned that consumer protection may be limited for some products or services, including lack of access to comprehensive information.", "The document does not certify the disclosure quality of a particular offer."),
    ("mica-finfluencers-2025", "esa25", "Why did the 2025 EU warning mention finfluencers?", "The authorities highlighted aggressive crypto promotion on social media by finfluencers as a reason for consumers to take care when evaluating products and services.", "A popular endorsement is not a verified source of risk or regulatory status."),
    ("mica-supervision-2025", "esa25", "How did the EU authorities describe MiCA supervision in 2025?", "The October 2025 publication said MiCA had applied to certain crypto-assets since December 2024 and established a supervisory regime at national and EU levels.", "A regime existing at publication does not prove a named service provider is authorised today."),
    ("defi-market-share-2025", "eba25", "How large did EBA and ESMA estimate DeFi was in their 2025 review?", "The joint report summary estimated value locked in DeFi at about four percent of global crypto-asset market value at the time of its analysis.", "This is a historical estimate; it must never be displayed as a live market share."),
    ("defi-adoption-2025", "eba25", "How did EBA and ESMA compare EU DeFi adoption with other economies?", "The 2025 summary described EU DeFi adoption as above the global average yet below several other developed economies.", "The comparison is a dated assessment, not a live ranking."),
    ("defi-hacks-2025", "eba25", "What relationship did EBA and ESMA observe between DeFi size and hacks?", "EBA and ESMA said the number of DeFi hacks and the value of stolen assets had generally moved with DeFi market size in their analysis.", "The observation is historical and does not predict breaches at an individual protocol."),
    ("defi-dex-share-2025", "eba25", "What did the 2025 EU report say about decentralised-exchange trading share?", "The report summary described decentralised-exchange flows as around ten percent of global spot crypto trading volumes in its analysis.", "This figure is a dated estimate and must not be presented as today's trading share."),
    ("defi-mev-2025", "eba25", "What did EBA and ESMA say about maximal extractable value in DeFi?", "The joint summary described MEV effects as widespread in DeFi and said their negative externalities would require technical solutions.", "That analysis does not evaluate the protections of any named transaction or protocol."),
    ("defi-leverage-2025", "eba25", "Why did the EU report flag leverage in crypto lending?", "The EBA and ESMA analysis listed excessive leverage among risks of crypto lending, borrowing and staking business models.", "It is a general risk category, not a finding that a particular service is over-leveraged."),
    ("defi-information-asymmetry-2025", "eba25", "What information imbalance did the EU crypto-lending report flag?", "The joint report listed information asymmetries among the risks of crypto lending, borrowing and staking services.", "A named provider's disclosure still needs examination on its own terms."),
    ("defi-rehypothecation-2025", "eba25", "Why did the EU authorities mention rehypothecation in crypto lending?", "The 2025 report identified possible systemic risks from rehypothecation and collateral chains among the risk channels it analysed.", "The report is not proof that any specific customer assets were reused."),
    ("defi-collateral-changes-2025", "eba25", "What collateral information might a crypto-lending user lack?", "EBA and ESMA said some users might receive insufficient information about changes to collateral requirements in crypto lending and related services.", "This is a disclosure-risk observation, not a finding about any specific contract."),
    ("defi-fees-2025", "eba25", "What fee disclosures did the EU crypto-lending analysis call into question?", "The joint report noted that users might receive insufficient information about fees for lending, borrowing and staking services.", "The source does not establish what an individual platform currently charges."),
    ("defi-yields-2025", "eba25", "What did EBA and ESMA say about disclosure of staking yields?", "The report said users might receive insufficient information about interest rates paid or yields in crypto lending and staking services.", "A quoted yield should be checked against current terms and risk, outside this historical record."),
    ("fraud-ai-voices-2025", "esaFraud", "How can AI-generated voices complicate crypto-fraud checks?", "The EU supervisors' December 2025 announcement said AI-generated voices or videos can imitate friends or family, making financial scams harder to spot.", "This consumer warning cannot authenticate or identify a particular call or video."),
    ("fraud-phishing-2025", "esaFraud", "Which phishing tactic did the EU fraud factsheet announcement cover?", "The ESAs said their new consumer factsheets explain phishing as one of the common tricks used in online financial and crypto scams.", "The announcement describes a fraud pattern; a particular message needs independent verification."),
    ("fraud-impersonation-2025", "esaFraud", "Why did the EU supervisors highlight impersonation scams?", "The December 2025 announcement listed impersonation among the tricks consumers should learn to recognise in online and crypto-related fraud.", "The source does not establish whether a specific sender is an impersonator."),
    ("fraud-ponzi-2025", "esaFraud", "Did the 2025 EU consumer factsheets cover Ponzi schemes?", "The EU authorities said their factsheets include Ponzi schemes among the fraud patterns explained to consumers.", "This is an educational classification, not a claim about a particular investment."),
    ("fraud-message-source-2025", "esaFraud", "What did EU supervisors advise before acting on a suspicious message?", "The December 2025 announcement recommended pausing to think and checking the source of a message before acting.", "That general precaution does not certify any individual communication."),
    ("fraud-personal-data-2025", "esaFraud", "What personal-information precaution did the EU fraud announcement give?", "The authorities advised consumers never to share personal or banking information in response to suspected scams.", "This is general educational guidance, not an assessment of a specific sender."),
    ("fraud-technology-2025", "esaFraud", "How did the ESAs say technology can affect online fraud?", "The 2025 announcement said AI and blockchain technology can make frauds and scams more convincing and harder to detect.", "Technology alone does not prove that an individual project or transaction is fraudulent."),
    ("group-encrypted-crypto-2025", "finra25", "How did FINRA describe crypto pitches in encrypted investment groups?", "FINRA's December 2025 alert described bad actors using encrypted group chats to promote lesser-known crypto-assets, often leaving investors with losses they cannot recover.", "This is a reported scam pattern rather than a finding about a specific group."),
    ("group-mixed-pitches-2025", "finra25", "Can one fraudulent investment group pitch both stocks and crypto?", "FINRA reported that some fraudulent groups solicit investors to buy stocks and crypto through communications within the same group.", "The report describes complaints and observed tactics, not every investment group."),
    ("group-professional-impersonation-2025", "finra25", "How might a group impersonate a registered investment professional?", "FINRA described scammers copying a real professional's name and publicly available details to create a false appearance of legitimacy.", "A professional's name in a chat does not authenticate who is speaking."),
    ("group-deepfake-2025", "finra25", "What role can deepfake videos play in investment-group scams?", "The FINRA alert reported deepfake videos impersonating known investment professionals in social-media investment pitches.", "A video appearance alone does not verify an endorsement or a person's identity."),
    ("group-uninvited-2025", "finra25", "What did FINRA say about being added to an investment chat without asking?", "FINRA said some investors were placed into encrypted group chats without prior contact as part of investment-group scam patterns.", "Unexpected membership is a reason to investigate, not proof by itself of fraud."),
    ("group-verify-2025", "finra25", "How did FINRA recommend checking a claimed investment professional?", "FINRA recommended using BrokerCheck and comparing the person's name, firm and location with independent research.", "A matching name may be impersonated; checking a listing alone does not authenticate the person messaging you."),
    ("group-research-2025", "finra25", "What independent research did FINRA recommend before following a group tip?", "FINRA advised searching for the group and investment product independently rather than trusting an unsolicited encrypted-chat pitch.", "This describes an investor diligence step, not a guarantee of safety."),
    ("group-loss-recovery-2025", "finra25", "How can a scam group exploit someone after a trading loss?", "FINRA reported scammers promising to recover earlier losses if the investor transferred more funds into their account.", "The alert describes a reported pressure tactic and does not assess a particular recovery service."),
    ("group-reporting-2025", "finra25", "Where did FINRA direct targets of investment-group scams to report concerns?", "FINRA invited regulatory tips and pointed potential criminal or cybercrime reports to law enforcement and the FBI's IC3.", "Reporting paths in a 2025 US alert may change; check the authorities' current pages before filing."),
    ("group-solicitation-2025", "finra25", "Which social channels did FINRA associate with investment-group pitches?", "FINRA described advertisements on social-media channels followed by one-to-one or group conversations in encrypted messaging apps.", "The use of a particular app does not itself establish that an offer is fraudulent."),
    ("sec24-fake-app", "secScams24", "Can an app-store listing prove that a crypto investment platform is genuine?", "The May 2024 SEC staff alert said scammers may use a widely available app or a plausible-looking fake website to make a fraudulent investment seem legitimate.", "App distribution is not independent verification of an investment platform."),
    ("sec24-small-withdrawal", "secScams24", "Why might a scam platform permit a small early withdrawal?", "The SEC staff described scammers letting targets withdraw a small purported profit to gain their trust before soliciting larger investments.", "A successful small withdrawal does not establish whether an individual platform is sound."),
    ("sec24-withdrawal-tax", "secScams24", "What did the SEC alert say about taxes demanded before withdrawal?", "The SEC staff described scammers inventing extra fees or taxes when a victim tries to withdraw purported investment proceeds.", "A payment demand should be examined independently; the alert does not judge an individual account."),
    ("sec24-ai-bots", "secScams24", "How can a claim about AI trading bots be used in a crypto scam?", "The SEC staff warned that scammers may claim AI bots can find superior crypto-related investments as a way to attract investors.", "A marketing claim about AI is not evidence that any particular system performs as promised."),
    ("sec24-deepfake-loved-ones", "secScams24", "Whose voices or faces can scammers imitate with deepfakes?", "The SEC alert described AI-generated imitations of celebrities, officials and loved ones used to build trust or seek funds.", "The warning does not authenticate an individual video or voice recording."),
    ("sec24-hijacked-account", "secScams24", "Can an investment pitch from a friend's social account still be suspicious?", "SEC staff warned that attackers can hijack friends' or family members' social accounts and post investment pitches in their names.", "A familiar account alone does not identify who controlled it when the message was sent."),
    ("sec24-memecoin-presale", "secScams24", "How can a memecoin presale be used in a pump-and-dump scheme?", "The SEC alert described promoters touting a memecoin on social media, sometimes as a presale, to drive purchases before promoters sell.", "The scenario is a risk pattern, not a finding about a named token."),
    ("sec24-refund-trick", "secScams24", "What fake refund story can extract an extra payment from an investor?", "The SEC staff warned that scammers may falsely claim they deposited money by mistake and ask a target to refund funds never actually sent.", "A claimed account credit needs independent confirmation."),
    ("sec24-recovery-key", "secScams24", "Why is a recovery service asking for a crypto private key a warning sign?", "The 2024 SEC alert warned that scammers may target past victims by requesting private keys or advance payments under the pretext of recovering lost funds.", "The warning does not evaluate a particular recovery provider."),
    ("sec24-fomo", "secScams24", "How did SEC staff link fear of missing out with crypto investment pitches?", "The alert cautioned investors against fear of missing out on a purported new or cutting-edge investment opportunity.", "Novelty does not establish the merits or fraud status of any particular opportunity."),
    ("yield22-deposit-comparison", "secYield22", "Why is a crypto interest account different from an insured bank deposit?", "The SEC's February 2022 bulletin distinguished crypto interest-bearing accounts from bank and credit-union deposits, which benefit from banking regulation and specified deposit-insurance protections.", "The source compares products at publication, not current coverage for an individual account."),
    ("yield22-sipc-market-loss", "secYield22", "Does SIPC insurance reimburse losses from falling security prices?", "The SEC bulletin stated that SIPC protection for qualifying broker failures does not cover losses caused by a decline in the market value of securities.", "The exact coverage for a current account requires checking applicable current rules."),
    ("yield22-sipc-crypto", "secYield22", "Did the SEC bulletin say SIPC covers most crypto assets?", "The February 2022 investor bulletin said SIPC protection did not cover the loss of most crypto assets or unregistered investment contracts.", "The statement is dated and does not determine protection for a particular asset today."),
    ("yield22-lending-use", "secYield22", "How might a crypto interest account generate its advertised return?", "The SEC bulletin explained that providers may lend deposited crypto assets to borrowers or pursue other crypto-related activities to fund interest payments.", "A particular provider's present activity must be checked separately."),
    ("yield22-illiquidity", "secYield22", "What liquidity risk did the SEC identify for crypto interest accounts?", "The SEC listed illiquidity and crypto market volatility among risks affecting assets held through interest-bearing accounts.", "This identifies general historical risks rather than a current liquidity reading."),
    ("yield22-company-failure", "secYield22", "What happens to an interest-account holder if the crypto company fails?", "The bulletin identified company failure or bankruptcy as a risk that can adversely affect deposited crypto holdings.", "It did not determine recovery rights for any specific failure; those depend on applicable facts and law."),
    ("yield22-untradable-asset", "secYield22", "Can a crypto asset held in an interest account become untradable?", "The SEC bulletin identified a risk that a crypto asset's market could disappear and the asset might no longer trade anywhere.", "This is a possible outcome, not a prediction for a named asset."),
    ("yield22-fraud-technical", "secYield22", "Which operational threats did the SEC list for crypto interest accounts?", "The bulletin listed potential fraud, technical glitches, hackers and malware among risks to crypto assets deployed by an interest-account company.", "The source does not assess any named service's present security."),
    ("yield22-blockfi-registration", "secYield22", "What did the SEC's 2022 BlockFi example say about registration?", "The SEC bulletin recounted an order finding that BlockFi Interest Accounts were securities offered without registration at the time of that action.", "The example is a dated specific enforcement outcome, not a rule classifying every crypto yield product."),
    ("yield22-blockfi-collateral", "secYield22", "Why did the SEC bulletin mention BlockFi's collateral statement?", "The bulletin recounted an SEC order finding BlockFi made a materially false or misleading statement about collateral practices, understating lending-program risk.", "The finding concerns the conduct in that order, not another company's collateral arrangements."),
    ("relation24-wrong-number", "secRelation24", "How can a wrong-number message start a relationship investment scam?", "The September 2024 joint alert described scammers pretending to contact the wrong person to begin a conversation and build trust.", "An unexpected message alone does not prove fraud by its sender."),
    ("relation24-platform-switch", "secRelation24", "Why might a scammer move a conversation to another messaging platform?", "The joint investor alert said fraudsters may move conversations away from the initial platform to a different, sometimes unmonitored, space.", "This is a described tactic, not a diagnosis of a particular conversation."),
    ("relation24-long-con", "secRelation24", "What does the joint investor alert mean by a relationship investment 'long con'?", "The alert described trust developing through friendship, romance or financial advice over time before an investment request appears.", "The pattern does not prove the intentions of a specific person."),
    ("relation24-fake-ico", "secRelation24", "How might an alleged initial coin offering conceal a direct transfer to a fraudster?", "The 2024 joint alert warned that a target may think they are investing in an ICO while funds actually go straight to a fraudster's wallet.", "The example does not evaluate a particular token offering."),
    ("relation24-payment-mismatch", "secRelation24", "Why check whether the payee matches the firm offering an investment?", "The joint alert flagged transfers to an individual or unrelated business rather than the expected investment firm as a suspicious payment pattern.", "It is an investigation prompt, not a definitive legal finding."),
    ("relation24-false-trade-screen", "secRelation24", "Can an investment dashboard show fabricated trades and gains?", "The 2024 alert said fraudsters can manipulate an online account or show fake screenshots and purported real-time trading data to suggest gains.", "A screen is not independent proof of an investor's assets."),
    ("relation24-loan-trap", "secRelation24", "How can a fake trading loan block a withdrawal?", "The joint alert warned that scammers may pretend to lend funds for trading and demand loan repayment before permitting withdrawal of principal or supposed profits.", "The source illustrates a fraud tactic without assessing a specific contract."),
    ("relation24-paid-testimonial", "secRelation24", "Why might a glowing testimonial inside an investment group mislead?", "The alert warned that scammers may pay actors or influencers to tout an opportunity and that members claiming huge profits might participate in the fraud.", "Testimonials need independent corroboration; a named speaker is not assessed here."),
    ("relation24-fake-celebrity", "secRelation24", "How can altered images create a false investment endorsement?", "The joint alert described altered or AI-generated photos or videos that falsely imply investment gains or celebrity endorsement.", "The statement does not establish whether an individual advertisement is authentic."),
    ("relation24-contact-independent", "secRelation24", "How should someone respond to an unexpected message claiming to be their financial institution?", "The joint alert advised against clicking links or using contact details supplied in an unexpected message claiming to come from an institution.", "Contact the institution through an independently verified channel for a current case."),
    ("chats25-expert-imposter", "secChats25", "What expert identities might a fraudulent investment group chat impersonate?", "The December 2025 SEC staff alert said a fake investment chat may pose as a famous financial expert, professor or CEO, including through a deepfake.", "This is a described scam tactic, not a finding about a named expert."),
    ("chats25-ai-signals", "secChats25", "Why are supposed AI trading signals in group chats worth checking?", "The SEC staff described chats promoting AI-generated stock picks or algorithms, and cited allegations involving investment clubs claiming AI-based signals.", "The named SEC case is an allegation; the alert does not validate any current algorithm."),
    ("chats25-app-store", "secChats25", "Does an investment group chat's recommended mobile app gain credibility from an app store?", "The SEC alert cautioned that availability in a familiar app store does not demonstrate legitimate trading or account activity.", "The warning does not evaluate an individual app."),
    ("chats25-frozen-account", "secChats25", "How can a fake regulatory account freeze be used to demand money?", "The 2025 SEC staff alert described fraudsters falsely claiming a regulator froze, or was about to freeze, an account to extract a fee, tax or deposit.", "A purported freeze must be checked independently through official channels."),
    ("chats25-form-crs", "secChats25", "What independent contact route did SEC staff suggest for a chat claiming to represent a broker?", "The SEC alert suggested contacting a professional through a phone number or website listed in the firm's Form CRS rather than contact details supplied in the chat.", "Confirm the form is genuine and current before relying on it."),
    ("chats25-entity-lookup", "secChats25", "How did SEC staff describe finding a genuine firm's Form CRS?", "The 2025 alert described searching Investor.gov for the firm, opening its details, and viewing its relationship summary.", "A firm record does not prove that an online sender works there."),
    ("chats25-professional-spoof", "secChats25", "Can a group chat impersonate a registered adviser or broker?", "The SEC staff warned that scammers may pretend to be registered brokers or advisers or may falsely associate a chat with a real firm.", "Check the sender through the firm's independently listed contact details."),
    ("chats25-stock-pump", "secChats25", "How can a group chat orchestrate a stock pump-and-dump?", "The SEC staff described chats using false stock tips to build a buying frenzy before promoters sell shares at investors' expense.", "The scenario is a general warning and does not classify any particular recommendation."),
    ("chats25-phony-license", "secChats25", "What did the SEC allege about trading platforms' regulatory licenses in the Morocoin case?", "The December 2025 alert summarized SEC complaint allegations that certain promoted crypto platforms falsely claimed regulatory licenses, including from the SEC.", "These are allegations in an enforcement complaint, not final judicial findings."),
    ("chats25-club-roles", "secChats25", "What 'professor' and 'assistant' roles appeared in the SEC's Morocoin allegations?", "The SEC alert reported complaint allegations that purported investment clubs used a professor to post market commentary and an assistant to communicate with members.", "These are case allegations, not a judgment about all groups using those titles."),
    ("finra-rel25-personal-info", "finraRelation25", "Why did FINRA say scammers ask about an online contact's personal life?", "FINRA's May 2025 article described scammers mirroring personal details and collecting information to build trust and later manipulate a target.", "This describes a pattern, not a conclusion about an individual friendship."),
    ("finra-rel25-small-first", "finraRelation25", "Why might a relationship scam start with a modest investment?", "FINRA described small initial solicitations as a way to strengthen confidence before a scammer requests larger investments.", "A small initial amount does not establish an offer's legitimacy."),
    ("finra-rel25-trade-screenshot", "finraRelation25", "Why might an online contact demand a screenshot of your trade?", "FINRA described stock-scam promoters requesting a screenshot confirming a specific trade had been executed.", "The article does not characterize any particular person's request."),
    ("finra-rel25-phony-dashboard", "finraRelation25", "What can a fabricated crypto-platform dashboard conceal?", "FINRA explained that a fake trading venue may display fictitious account growth even when funds went directly to scammers.", "A screenshot is not independent evidence of custody or holdings."),
    ("finra-rel25-unavailable-platform", "finraRelation25", "What may happen to a fake crypto platform when an investor tries to withdraw?", "FINRA warned that victims may discover their purported account cannot be withdrawn or that the site becomes inaccessible.", "It is an illustrative risk pattern, not an assessment of a named venue."),
    ("finra-rel25-independent-opinion", "finraRelation25", "Whose opinion might help evaluate an unfamiliar investment pitch?", "FINRA suggested asking an independent third party or an investment professional with no stake in the transaction to review an unfamiliar offer.", "A second opinion cannot guarantee an investment's safety."),
    ("finra-rel25-platform-control", "finraRelation25", "Which platform-control questions did FINRA recommend asking?", "FINRA suggested checking who controls a trading platform, its security measures, and how funds could be withdrawn.", "These questions require current independent checks on the actual operator."),
    ("finra-rel25-broker-history", "finraRelation25", "Can BrokerCheck reveal a promoter's disciplinary history?", "FINRA recommended BrokerCheck to review whether someone is or was registered and to inspect any disclosed disciplinary history.", "A registration match does not authenticate the person contacting you."),
    ("finra-rel25-guaranteed", "finraRelation25", "Why did FINRA flag supposedly guaranteed unusually high investment returns?", "The May 2025 FINRA article listed exaggerated or guaranteed returns among warning signs in relationship investment scams.", "A marketing promise alone does not quantify any individual product's actual risk."),
    ("finra-rel25-emotional-appeal", "finraRelation25", "What emotional pressure might appear in an investment relationship scam?", "FINRA described scammers appealing to family goals or other emotions to encourage a target to invest more money.", "An emotional appeal is a reason for caution, not proof of fraud."),
]


def build():
    documents = []
    for source_id, title, url, published, note in SOURCES.values():
        documents.append({"_id": source_id, "_type": "source", "title": title, "url": url,
                          "publishedAt": published, "kind": "official", "notes": note})
    for slug, key, title, claim, context in QUESTIONS:
        event_id = f"market-event-{slug}"
        source_id = SOURCES[key][0] if key in SOURCES else key
        documents += [
            {"_id": event_id, "_type": "marketEvent", "title": title,
             "summary": context, "observedAt": OBSERVED, "review": "needs-human-review"},
            {"_id": f"evidence-claim-{slug}", "_type": "evidenceClaim",
             "event": {"_type": "reference", "_ref": event_id},
             "source": {"_type": "reference", "_ref": source_id},
             "text": claim, "stance": "supports", "observedAt": OBSERVED},
        ]
    return documents


if __name__ == "__main__":
    OUTPUT.write_text(json.dumps(build(), indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {len(QUESTIONS)} questions and {len(SOURCES)} dated sources to {OUTPUT}")
